### ISSUE TITLE
Rename "human" output to "interactive"

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vegawallet#338]
Having a "human" output doesn't feel to be the right wording. What about lizard men and aliens ? This is too divisive.

Let's rename it "interactive".

**Comment by MuthuVega** [comment]
Tested OK on latest wallet

```
Muthus-MBP:vega muthupandianvadivelu$ vegawallet -o interactive network describe --network devnet
✗ You are running an unreleased version of the Vega wallet (v0.11.0+dev). Use it at your own risk!


Network
  Name:         devnet
  Address:      127.0.0.1:1789
  Token expiry: 168h0m0s
  Level:        info

API.GRPC
  Retries: 5
  Hosts:
    - n06.testnet.vega.xyz:3007
    - n07.testnet.vega.xyz:3007
    - n08.testnet.vega.xyz:3007
    - n09.testnet.vega.xyz:3007
    - n10.testnet.vega.xyz:3007
    - n11.testnet.vega.xyz:3007
    - n12.testnet.vega.xyz:3007
    - n13.testnet.vega.xyz:3007
    - n14.testnet.vega.xyz:3007
    - n15.testnet.vega.xyz:3007
    - n16.testnet.vega.xyz:3007
    - n17.testnet.vega.xyz:3007
    - n18.testnet.vega.xyz:3007
    - n19.testnet.vega.xyz:3007
    - n20.testnet.vega.xyz:3007

API.REST
  Hosts:
    - https://n04.d.vega.xyz

API.GraphQL
  Hosts:
    - https://n04.d.vega.xyz/query

Console
  Address: dev.vega.trading:1847

```
```
Muthus-MBP:vega muthupandianvadivelu$ vegawallet -o json network describe --network devnet
{"name":"devnet","logLevel":"info","tokenExpiry":"168h0m0s","port":1789,"host":"127.0.0.1","api":{"grpcConfig":{"hosts":["n06.testnet.vega.xyz:3007","n07.testnet.vega.xyz:3007","n08.testnet.vega.xyz:3007","n09.testnet.vega.xyz:3007","n10.testnet.vega.xyz:3007","n11.testnet.vega.xyz:3007","n12.testnet.vega.xyz:3007","n13.testnet.vega.xyz:3007","n14.testnet.vega.xyz:3007","n15.testnet.vega.xyz:3007","n16.testnet.vega.xyz:3007","n17.testnet.vega.xyz:3007","n18.testnet.vega.xyz:3007","n19.testnet.vega.xyz:3007","n20.testnet.vega.xyz:3007"],"retries":5},"restConfig":{"hosts":["https://n04.d.vega.xyz"]},"graphQLConfig":{"hosts":["https://n04.d.vega.xyz/query"]}},"Console":{"url":"dev.vega.trading","localPort":1847}}
Muthus-MBP:vega muthupandianvadivelu$ 
```

```
Muthus-MBP:vega muthupandianvadivelu$ vegawallet -h
The Vega wallet

Usage:
  vegawallet [command]

Examples:
  # Specify a custom Vega home directory
  vegawallet --home PATH_TO_DIR COMMAND
  
  # Change the output to JSON
  vegawallet --output json COMMAND
  
  # Disable colors on output using environment variable
  NO_COLOR=1 vegawallet COMMAND
  
  # Disable the verification of the program version
  vegawallet --no-version-check COMMAND

Available Commands:
  command     Provides utilities for interacting with commands
  help        Help about any command
  import      Import a wallet using the mnemonic
  info        Get wallet information
  init        Initialise the program
  key         Manage Vega wallets' keys
  list        List all registered wallets
  network     Manage networks
  service     Manage the Vega wallet's service
  sign        Sign a message using a Vega wallet key
  tx          Provides utilities for interacting with transactions
  verify      Verify a message against a signature
  version     Get the version of the program

Flags:
  -h, --help               help for vegawallet
      --home string        Specify the location of a custom Vega home
      --no-version-check   Do not check for new version of the Vega wallet
  -o, --output string      Specify the output format: [interactive json] (default "interactive")

Use "vegawallet [command] --help" for more information about a command.

```
